version: 2
updates:
  - directory: /
    groups:
      actions-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
    package-ecosystem: github-actions
    schedule:
      interval: monthly
