allowCompoundWords: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - fonts
  - git
  - lorem-ipsum
  - markdown
  - misc
  - npm
  - shell
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
ignoreRegExpList:
  - '\b[0-9A-Z]{12,14}\b'
language: en,ja
useGitignore: true
version: "0.2"
words:
  - antlr
  - chezmoi
  - choco
  - dind
  - dosbox
  - fastfetch
  - fnm
  - ghub
  - hkcu
  - hklm
  - imgbotconfig
  - izotope
  - jqlang
  - kito
  - kuron
  - kuroné
  - ollama
  - posh
  - psscriptanalyzer
  - tealdeer
  - tldr
  - unigetui
  - vcredist
  - vrchat
  - vrcx
