allowCompoundWords: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - fonts
  - git
  - lorem-ipsum
  - markdown
  - misc
  - npm
  - shell
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
  - test
ignoreRegExpList:
  - '\b[0-9A-Z]{12,14}\b'
  - Install-WingetApps .*\.
language: en,ja
useGitignore: true
version: "0.2"
words:
  - alsa
  - apic
  - antlr
  - audioin
  - biosapic
  - choco
  - dind
  - dsound
  - ghub
  - hkcu
  - hklm
  - hpet
  - hwvirtex
  - iexplore
  - imgbotconfig
  - ioapic
  - izotope
  - kito
  - kuron
  - kuroné
  - modifyvm
  - mswin
  - maxon
  - nprocessors
  - tldr
  - usbxhci
  - useb
  - vbguest
  - vboxsvga
  - vcredist
  - vrchat
  - vrcx
  - vtxux
  - vtxvpid
  - wkhtmltopdf
  - wkhtmltox
