allowCompoundWords: true
dictionaries:
  - cpp
  - en_US
  - en-gb
  - fonts
  - git
  - lorem-ipsum
  - markdown
  - misc
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,ja
useGitignore: true
version: "0.2"
words:
  - antlr
  - choco
  - dind
  - imgbotconfig
  - izotope
  - kito
  - kuron
  - kuroné
  - maxon
  - tldr
  - vbguest
  - vrcx
  - wkhtmltopdf
