#!/bin/sh

# Validation
if [ $# -eq 0 ]; then
    echo "Usage: ./test win{7|8.1|10}"
    exit 255
fi

# Install some dependencies
if [ "$(uname)" == 'Darwin' ] && [ `which brew | wc -l` -eq 0 ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    xcode-select --install
fi
function app_install() {
    if [ `which ${1} | wc -l` -eq 0 ]; then
        if [ "$(uname)" != 'Darwin' ]; then
            echo "Unknown platform: $(uname)"
            exit 2
        fi
        shift
        brew update
        `brew cask install ${@}`
    fi
}
PLUGINS=`vagrant plugin list`
function plugin_install() {
if [ `echo ${PLUGINS} | grep ${1} | wc -l` -eq 0 ]; then
    vagrant plugin install ${1}
fi
}

app_install virtualbox virtualbox virtualbox-extension-pack
app_install vagrant vagrant
plugin_install vagrant-reload
plugin_install vagrant-windows-update

### Skip when exists
# vagrant box add designerror/windows-7
# vagrant box add opentable/win-8.1-enterprise-amd64-nocm
# vagrant box add Microsoft/EdgeOnWindows10

vagrant up --provision $1
