#!/bin/sh

# Validation
if [ $# -eq 0 ]; then
    echo "Usage: ./test {7|81|10}"
    exit 255
fi
if [ ! -d $1 ]; then
    echo "Unknown guest: ${1}"
    exit 1
fi

# Install some dependencies
if [ "$(uname)" == 'Darwin' ] && [ `which brew | wc -l` -eq 0 ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    xcode-select --install
fi
function brew_install() {
    if [ `which ${1} | wc -l` -eq 0 ]; then
        if [ "$(uname)" != 'Darwin' ]; then
            echo "Unknown platform: $(uname)"
            exit 2
        fi
        shift
        brew update
        `brew cask install ${@}`
    fi
}
PLUGINS=`vagrant plugin list`
function plugin_install() {
if [ `echo ${PLUGINS} | grep ${1} | wc -l` -eq 0 ]; then
    vagrant plugin install ${1}
fi
}

brew_install virtualbox virtualbox virtualbox-extension-pack
brew_install vagrant vagrant
plugin_install vagrant-reload
plugin_install vagrant-vbguest
plugin_install vagrant-windows-update

cd $1
vagrant up --provision
