# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?('vagrant-reload')
  raise 'vagrant-reload is not installed!'
end

Vagrant.configure('2') do |config|
  config.vm.box = 'designerror/windows-7'
  config.vm.communicator = 'winrm'
  config.vm.guest = :windows
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.cpus = 3
    vb.linked_clone = true
    vb.name = 'konstrui-windows-7'
    vb.memory = '3584'
    vb.customize [
      'modifyvm', :id,
      '--ioapic', 'on',
      '--vram', '128',
      '--usb', 'on',
      '--usbehci', 'on',
      '--accelerate3d', 'on',
    ]
    if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
      vb.customize [
        'modifyvm', :id,
        '--audio', 'dsound',
        '--audiocontroller', 'ac97'
      ]
    elsif (/darwin/ =~ RUBY_PLATFORM) != nil
      vb.customize [
        'modifyvm', :id,
        '--audio', 'coreaudio',
        '--audiocontroller', 'ac97'
      ]
    end
  end
  config.vm.provision 'Install chocolatey', type: 'shell', path: '../setup.files/01.choco.ps1'
  config.vm.provision 'Install WMF5.1', type: 'shell', path: '../setup.files/02.wmf51.ps1'
  config.vm.provision :reload
  config.vm.provision 'windows-update'
  config.vm.provision :reload
  config.vm.provision 'Runtimes', type: 'shell', path: '../setup.files/04.runtimes.ps1'
end
